obj-$(CONFIG_TOUCHSCREEN_GT9XX)		+= gt9xx/
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_FT5435)	+= ft5435/
obj-y	+= lct_tp_fm_info.o
obj-y	+= lct_ctp_selftest.o
obj-y	+= lct_ctp_upgrade.o
obj-y	+= lct_if_ctp_upgrade.o
