obj-$(CONFIG_GT9XX_TOUCHPANEL_DRIVER)		+= gt9xx/
obj-$(CONFIG_TOUCHSCREEN_FT5435)	+= ft5435/
obj-y	+= lct_tp_fm_info.o
obj-y	+= lct_ctp_selftest.o
obj-y	+= lct_ctp_upgrade.o
obj-y	+= lct_if_ctp_upgrade.o
